services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www
    networks:
      - network

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:inception
    depends_on:
      - wordpress
    ports:
      - 21:21
    volumes:
      - wordpress_data:/var/www/
    networks:
      - network
    env_file:
      - .env
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:inception
    ports:
      - 6379:6379
    volumes:
      - wordpress_data:/var/www
    networks:
      - network
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:inception
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - network
    env_file:
      - .env
    restart: always

  portainer:
    container_name: portainer
    build: ./requirements/bonus/Portainer
    image: portainer:inception
    ports:
      - 9443:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - network
    restart: always

  website:
    container_name: website
    build: ./requirements/bonus/website
    image: website:inception
    ports:
      - 7546:7546
    networks:
      - network
    env_file:
      - .env
    restart: always


volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device:  /home/eamghar/data/db

  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device:  /home/eamghar/data/wp

networks:
  network:
    driver: bridge
